# Generated by Django 6.0.6 on 2026-07-09 23:57

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0237_module_remove_local_context_data'),
        ('extras', '0140_imageattachment_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('physical_address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('portal_url', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('version', models.CharField(max_length=50)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_of_support', models.DateField(blank=True, null=True)),
                ('long_term_support', models.BooleanField(default=False)),
                ('documentation_url', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_versions', to='dcim.platform')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('platform', 'version'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SoftwareImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('file_name', models.CharField(max_length=255)),
                ('checksum', models.CharField(blank=True, max_length=255)),
                ('hashing_algorithm', models.CharField(blank=True, max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True)),
                ('default_image', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='netbox_dlm.softwareversion')),
            ],
            options={
                'ordering': ('software_version', 'file_name'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DeviceSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_software', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices_running', to='netbox_dlm.softwareversion')),
            ],
            options={
                'verbose_name': 'Device software',
                'verbose_name_plural': 'Device software',
                'ordering': ('device',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True)),
                ('status', models.CharField(default='awaiting_review', max_length=30)),
                ('severity', models.CharField(blank=True, max_length=10)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_v2_score', models.FloatField(blank=True, null=True)),
                ('cvss_v3_score', models.FloatField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('affected_software', models.ManyToManyField(blank=True, related_name='cves', to='netbox_dlm.softwareversion')),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVEs',
                'ordering': ('-published_date', 'cve_id'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ValidatedSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('preferred', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
                ('device_roles', models.ManyToManyField(blank=True, related_name='+', to='dcim.devicerole')),
                ('device_types', models.ManyToManyField(blank=True, related_name='+', to='dcim.devicetype')),
                ('devices', models.ManyToManyField(blank=True, related_name='+', to='dcim.device')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validated_rules', to='netbox_dlm.softwareversion')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Validated software',
                'ordering': ('-preferred', 'software_version', 'start'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(default='open', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='netbox_dlm.cve')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='dcim.device')),
                ('software_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='netbox_dlm.softwareversion')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ('cve', 'software_version', 'device'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HardwareNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('end_of_sale', models.DateField(blank=True, null=True)),
                ('end_of_support', models.DateField(blank=True, null=True)),
                ('end_of_security_patches', models.DateField(blank=True, null=True)),
                ('end_of_sw_releases', models.DateField(blank=True, null=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardware_notices', to='dcim.devicetype')),
                ('module_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardware_notices', to='dcim.moduletype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('end_of_support', 'device_type', 'module_type'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('device_type__isnull', False)), fields=('device_type',), name='netbox_dlm_hardwarenotice_unique_device_type'), models.UniqueConstraint(condition=models.Q(('module_type__isnull', False)), fields=('module_type',), name='netbox_dlm_hardwarenotice_unique_module_type')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=3)),
                ('support_level', models.CharField(blank=True, max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('devices', models.ManyToManyField(blank=True, related_name='lifecycle_contracts', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='netbox_dlm.provider')),
            ],
            options={
                'ordering': ('provider', 'name'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'name'), name='netbox_dlm_contract_unique_provider_name')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(fields=('platform', 'version'), name='netbox_dlm_softwareversion_unique_platform_version'),
        ),
        migrations.AddConstraint(
            model_name='softwareimagefile',
            constraint=models.UniqueConstraint(fields=('software_version', 'file_name'), name='netbox_dlm_softwareimagefile_unique_version_filename'),
        ),
        migrations.AddConstraint(
            model_name='vulnerability',
            constraint=models.UniqueConstraint(fields=('cve', 'software_version', 'device'), name='netbox_dlm_vulnerability_unique_cve_software_device'),
        ),
    ]
