# Generated by Django 6.0.6 on 2026-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0237_module_remove_local_context_data'),
        ('netbox_dlm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedsoftware',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.platform'),
        ),
    ]
