# Generated by Django 6.0.6 on 2026-07-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0237_module_remove_local_context_data'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_dlm', '0002_validatedsoftware_platforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwareversion',
            name='release_designation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='softwareversion',
            constraint=models.UniqueConstraint(condition=models.Q(('release_designation', ''), _negated=True), fields=('platform', 'release_designation'), name='netbox_dlm_softwareversion_unique_platform_release_designation'),
        ),
    ]
