# Generated by Django 6.0.6 on 2026-08-01 15:55

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0237_module_remove_local_context_data'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_dlm', '0003_softwareversion_release_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemRolePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inventory item role platform',
                'verbose_name_plural': 'Inventory item role platforms',
                'ordering': ('role',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryItemSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inventory item software',
                'verbose_name_plural': 'Inventory item software',
                'ordering': ('inventory_item',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='vulnerability',
            options={'ordering': ('cve', 'software_version', 'device', 'inventory_item')},
        ),
        migrations.RemoveConstraint(
            model_name='vulnerability',
            name='netbox_dlm_vulnerability_unique_cve_software_device',
        ),
        migrations.AddField(
            model_name='validatedsoftware',
            name='inventory_item_roles',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.inventoryitemrole'),
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='dcim.inventoryitem'),
        ),
        migrations.AddConstraint(
            model_name='vulnerability',
            constraint=models.UniqueConstraint(fields=('cve', 'software_version', 'device', 'inventory_item'), name='netbox_dlm_vulnerability_unique_cve_software_device'),
        ),
        migrations.AddField(
            model_name='inventoryitemroleplatform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.platform'),
        ),
        migrations.AddField(
            model_name='inventoryitemroleplatform',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_platform', to='dcim.inventoryitemrole'),
        ),
        migrations.AddField(
            model_name='inventoryitemroleplatform',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='inventoryitemsoftware',
            name='inventory_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_software', to='dcim.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventoryitemsoftware',
            name='software_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_running', to='netbox_dlm.softwareversion'),
        ),
        migrations.AddField(
            model_name='inventoryitemsoftware',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
    ]
