# Generated by Django 6.0.6 on 2026-08-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0237_module_remove_local_context_data'),
        ('netbox_dlm', '0004_inventoryitemroleplatform_inventoryitemsoftware_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.platform'),
        ),
    ]
